### PR TITLE
xen: create subpackage xen-libs

### PR DESCRIPTION
**Pull request by undu**
I'm opening the PR as I understand this is the upstream of https://aur.archlinux.org/packages/xen/.

Having the new supackage allows to install headers and libraries (C and ocaml) without
installing the xen package. This is useful for development purposes.

Please let me know if there's something I can enhance to get it pushed into the aur.
Currently the ocaml packages that depend on xen can't be built in arch because they depend on the outdated aur package 'xenstore', I'd hoping to fix this by creating the package xen-libs.

### CODE REVIEW

**Comment by refutationalist** [comment]
It'll be a bit before the package appears on AUR as the resulting packages do not work on my machines.

**Comment by undu** [comment]
How do the package break? The separation should not affect the xen binary.

It might be that I missed some .so files. I'll make a diff the lib and include libraries between old and new packages to check that out 

Other than that the xen package probably needs to depend on xen-libs because of the tools binaries depend on it.
Another option is to create the xen-tools package to separate these from the main xen package as well.

I've just gone on vacation so unfortunately I can't do this work immediately, sorry about that. I'm fine if the merge is reverted to fix these issues at a later day if the breakage inconveniences you

**Comment by refutationalist** [comment]
xen does need xen-libs.  Additionally, xen installs some stuff it needs in libexec and elsewhere to operate that end up in neither package, so just removing /usr/lib and /usr/include isn't quite enough.

Might not be as important if you aren't building qemu with xen, but most people do need that at the moment.

**Comment by refutationalist** [comment]
I've reverted the merge request as it was broken.   I'm not sure creating a libs package is a good idea, and I'm looking into guidance as to how to move forward.

**Comment by undu** [comment]
Hmmm, I was unable to install the Xen because of lack of space in the EFI partitino. I don't I Will be able to test the breakages properly.

At this point I'm thinking about creating xen-libs as an independent package that conflicts with Xen so other developers that can't or won't install xen still can develop for it

**Comment by refutationalist** [comment]
You can set efi and boot directories at build time with variables fed to makepkg.

boot_dir, efi_dir and efi_mountpoint will change where things are put.

**Pull request merged**
